package finalprojectuts;

import static finalprojectuts.ViewModel.listDataPakaian;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static finalprojectuts.ViewModel.jumlahPakaian;

public class PakaianUI extends BaseUI {

    /**
     * Creates new form PakaianUi
     */
    public cPakaian[] arrayPakaian = new cPakaian[5];

    public PakaianUI() {
        initComponents();
    }

    public PakaianUI(cPakaian[] cPakaian) {
        if (cPakaian != null) {
            this.arrayPakaian = cPakaian;
        }
        initComponents();
    }

    void addPakaianToTable(Object[] data) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(data);
    }

    private void addPakaian(String merk, double harga, PakaianListener.TambahPakaian listener) {
        if (jumlahPakaian < 5) {
            boolean ada = false;
            for (int i = 0; i < jumlahPakaian; i++) {
                if (arrayPakaian[i].getMerk().equalsIgnoreCase(merk)) {
                    ada = true;
                    break;
                }
            }
            if (ada == true) {
                listener.merkSudahAda("Merk sudah ada");
            } else {
                arrayPakaian[jumlahPakaian] = new cPakaian(merk, harga);
                listDataPakaian[0][0] = arrayPakaian[jumlahPakaian].getMerk();
                listDataPakaian[0][1] = String.valueOf(arrayPakaian[jumlahPakaian].getHarga());
                addPakaianToTable(listDataPakaian[0]);
                jumlahPakaian++;
            }
        } else {
            listener.kapasitasPenuh("Kapasitas penuh!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPakaian = new javax.swing.JPanel();
        jLabelPakaian = new javax.swing.JLabel();
        jButtonBackPakaian = new javax.swing.JButton();
        jButtonAddPakaian = new javax.swing.JButton();
        jButtonUbahPakaian = new javax.swing.JButton();
        jButtonRemovePakaian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(694, 666));

        jPanelPakaian.setBackground(new java.awt.Color(255, 102, 102));
        jPanelPakaian.setPreferredSize(new java.awt.Dimension(694, 666));

        jLabelPakaian.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelPakaian.setForeground(new java.awt.Color(97, 97, 41));
        jLabelPakaian.setText("PAKAIAN");

        jButtonBackPakaian.setBackground(new java.awt.Color(255, 102, 102));
        jButtonBackPakaian.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButtonBackPakaian.setForeground(new java.awt.Color(97, 97, 41));
        jButtonBackPakaian.setText("KEMBALI");
        jButtonBackPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPakaianActionPerformed(evt);
            }
        });

        jButtonAddPakaian.setBackground(new java.awt.Color(135, 199, 244));
        jButtonAddPakaian.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonAddPakaian.setForeground(new java.awt.Color(97, 97, 41));
        jButtonAddPakaian.setText("TAMBAH");
        jButtonAddPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPakaianActionPerformed(evt);
            }
        });

        jButtonUbahPakaian.setBackground(new java.awt.Color(135, 199, 244));
        jButtonUbahPakaian.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonUbahPakaian.setForeground(new java.awt.Color(97, 97, 41));
        jButtonUbahPakaian.setText("UBAH");
        jButtonUbahPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahPakaianActionPerformed(evt);
            }
        });

        jButtonRemovePakaian.setBackground(new java.awt.Color(135, 199, 244));
        jButtonRemovePakaian.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonRemovePakaian.setForeground(new java.awt.Color(97, 97, 41));
        jButtonRemovePakaian.setText("HAPUS");
        jButtonRemovePakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePakaianActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MERK", "HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAKAIANID");

        javax.swing.GroupLayout jPanelPakaianLayout = new javax.swing.GroupLayout(jPanelPakaian);
        jPanelPakaian.setLayout(jPanelPakaianLayout);
        jPanelPakaianLayout.setHorizontalGroup(
            jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPakaianLayout.createSequentialGroup()
                .addGroup(jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPakaianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPakaian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBackPakaian))
                    .addGroup(jPanelPakaianLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanelPakaianLayout.createSequentialGroup()
                                .addComponent(jButtonAddPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUbahPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemovePakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPakaianLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPakaianLayout.setVerticalGroup(
            jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPakaianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPakaian)
                    .addComponent(jButtonBackPakaian))
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(jPanelPakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUbahPakaian)
                    .addComponent(jButtonAddPakaian)
                    .addComponent(jButtonRemovePakaian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPakaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPakaian, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonAddPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPakaianActionPerformed

        String m = JOptionPane.showInputDialog(this, "Masukkan Merk");
        double h = Double.parseDouble(JOptionPane.showInputDialog(this, "Masukkan Harga"));

        addPakaian(m, h, new PakaianListener.TambahPakaian() {
            @Override
            public void merkSudahAda(String message) {
                JOptionPane.showMessageDialog(PakaianUI.this, message);
            }

            @Override
            public void kapasitasPenuh(String message) {
                JOptionPane.showMessageDialog(PakaianUI.this, "Kapasitas penuh!");
            }
        });

    }//GEN-LAST:event_jButtonAddPakaianActionPerformed

    private void jButtonUbahPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahPakaianActionPerformed
        //asumsinya yg berubah adalah data harga saja
        boolean ketemu = false;
        int indeks = 0;
        String id = JOptionPane.showInputDialog(this, "Masukkan Merk");
        //cek cari dulu ID di Array Pelanggan
        for (int i = 0; i < jumlahPakaian; i++) {
            indeks = i;
            if (arrayPakaian[i].getMerk().equalsIgnoreCase(id)) {
                ketemu = true;
                break;
            }
        }
        if (ketemu == true) {
            String h = JOptionPane.showInputDialog(this, "Masukkan Harga Baru");
            int j = JOptionPane.showConfirmDialog(this, "Yakin diubah");
            if (j == 0) {
                arrayPakaian[indeks].setHarga(Double.parseDouble(h));
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                //update sel data pada baris indeks, kolom ke-2, dengan data a1
                model.setValueAt(h, indeks, 1);
                JOptionPane.showMessageDialog(this, "Berhasil diperbarui...");
            } else {
                JOptionPane.showMessageDialog(this, "Batal update!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Merk tidak ada!");
        }
    }//GEN-LAST:event_jButtonUbahPakaianActionPerformed

    private void jButtonRemovePakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePakaianActionPerformed
        //cai dulu merk di array pelanggan
        boolean ketemu = false;
        int indeks = 0;
        String id = JOptionPane.showInputDialog(this, "Masukkan Merk");
        //cek cari dulu ID di Array Pelanggan
        for (int i = 0; i < jumlahPakaian; i++) {
            indeks = i;
            if (arrayPakaian[i].getMerk().equalsIgnoreCase(id)) {
                ketemu = true;
                break;
            }
        }
        if (ketemu == true) {
            int j = JOptionPane.showConfirmDialog(this, "Yakin dihapus");
            if (j == 0) {
                for (int i = 0; i < jumlahPakaian; i++) {
                    if (i == jumlahPakaian - 1) {
                        arrayPakaian[i] = null;
                    } else {
                        arrayPakaian[i] = arrayPakaian[i + 1];
                    }
                }
                jumlahPakaian--;
                //update isi tabel
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(indeks);
                JOptionPane.showMessageDialog(this, "Berhasil dihapus...");
            } else {
                JOptionPane.showMessageDialog(this, "Batal hapus!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Merk tidak ada!");
        }
    }//GEN-LAST:event_jButtonRemovePakaianActionPerformed

    private void jButtonBackPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPakaianActionPerformed
        // TODO add your handling code here:
        MenuUI menu = new MenuUI(arrayPakaian);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackPakaianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PakaianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PakaianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PakaianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PakaianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PakaianUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPakaian;
    private javax.swing.JButton jButtonBackPakaian;
    private javax.swing.JButton jButtonRemovePakaian;
    private javax.swing.JButton jButtonUbahPakaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPakaian;
    private javax.swing.JPanel jPanelPakaian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
