package finalprojectuts;

import static finalprojectuts.ViewModel.totalbiaya;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import static finalprojectuts.ViewModel.jumlahPembeli;
import static finalprojectuts.ViewModel.jumlahPakaian;
import static finalprojectuts.ViewModel.listDataPenjualan;

public class PenjualanUI extends BaseUI {

    /**
     * Creates new form PenjualanUI
     */ 
    public cTransaksi arrayPenjualan = null;
    public cPakaian[] arrayPakaian;

    public PenjualanUI() {
        initComponents();
    }
    
    public PenjualanUI(cPakaian[] cPakaian) {
        if (cPakaian != null) {
            this.arrayPakaian = cPakaian;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPenjualan = new javax.swing.JPanel();
        jLabelPenjualan = new javax.swing.JLabel();
        jButtonBackPenjualan = new javax.swing.JButton();
        jButtonAddPenjualan = new javax.swing.JButton();
        jButtonBatalPenjualan = new javax.swing.JButton();
        jButtonAddItemPenjualan = new javax.swing.JButton();
        jButtonRemoveItemPenjualan = new javax.swing.JButton();
        jLabelPembeliPenjualan = new javax.swing.JLabel();
        jLabelKodePenjualan = new javax.swing.JLabel();
        jLabelTotalBiayaPenjualan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePenjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(694, 666));

        jPanelPenjualan.setBackground(new java.awt.Color(255, 102, 102));
        jPanelPenjualan.setPreferredSize(new java.awt.Dimension(694, 666));

        jLabelPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jLabelPenjualan.setText("PENJUALAN");

        jButtonBackPenjualan.setBackground(new java.awt.Color(255, 102, 102));
        jButtonBackPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButtonBackPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jButtonBackPenjualan.setText("KEMBALI");
        jButtonBackPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackPenjualanActionPerformed(evt);
            }
        });

        jButtonAddPenjualan.setBackground(new java.awt.Color(135, 199, 244));
        jButtonAddPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonAddPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jButtonAddPenjualan.setText("TAMBAH");
        jButtonAddPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPenjualanActionPerformed(evt);
            }
        });

        jButtonBatalPenjualan.setBackground(new java.awt.Color(135, 199, 244));
        jButtonBatalPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonBatalPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jButtonBatalPenjualan.setText("BATAL");
        jButtonBatalPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalPenjualanActionPerformed(evt);
            }
        });

        jButtonAddItemPenjualan.setBackground(new java.awt.Color(135, 199, 244));
        jButtonAddItemPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonAddItemPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jButtonAddItemPenjualan.setText("TAMBAH PAKAIAN");
        jButtonAddItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemPenjualanActionPerformed(evt);
            }
        });

        jButtonRemoveItemPenjualan.setBackground(new java.awt.Color(135, 199, 244));
        jButtonRemoveItemPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButtonRemoveItemPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jButtonRemoveItemPenjualan.setText("HAPUS PAKAIAN");
        jButtonRemoveItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveItemPenjualanActionPerformed(evt);
            }
        });

        jLabelPembeliPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabelPembeliPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jLabelPembeliPenjualan.setText("Pembeli : ");

        jLabelKodePenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabelKodePenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jLabelKodePenjualan.setText("Kode : ");

        jLabelTotalBiayaPenjualan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabelTotalBiayaPenjualan.setForeground(new java.awt.Color(97, 97, 41));
        jLabelTotalBiayaPenjualan.setText("Total Biaya : ");

        jTablePenjualan.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Merk", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePenjualan);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAKAIANID");

        javax.swing.GroupLayout jPanelPenjualanLayout = new javax.swing.GroupLayout(jPanelPenjualan);
        jPanelPenjualan.setLayout(jPanelPenjualanLayout);
        jPanelPenjualanLayout.setHorizontalGroup(
            jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                        .addComponent(jLabelPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                        .addComponent(jButtonBackPenjualan))
                    .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPembeliPenjualan)
                            .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                                .addComponent(jButtonAddPenjualan)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBatalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddItemPenjualan)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemoveItemPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelKodePenjualan)
                            .addComponent(jLabelTotalBiayaPenjualan)
                            .addComponent(jScrollPane1))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPenjualanLayout.setVerticalGroup(
            jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPenjualan)
                    .addComponent(jButtonBackPenjualan))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddPenjualan)
                    .addComponent(jButtonBatalPenjualan)
                    .addComponent(jButtonAddItemPenjualan)
                    .addComponent(jButtonRemoveItemPenjualan))
                .addGap(26, 26, 26)
                .addComponent(jLabelPembeliPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKodePenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalBiayaPenjualan)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPenjualanActionPerformed
        //untuk menyiapkan object pembelian (container)
        //array object sepatu lewat tombol tambah sepatu
        String kd = JOptionPane.showInputDialog(this, "Masukkan Kode");
        String nm = JOptionPane.showInputDialog(this, "Masukkan Nama Pembeli");
        int jum = Integer.parseInt(JOptionPane.showInputDialog(this, "Berapa Sepatu"));
        arrayPenjualan = new cTransaksi(kd, jum);
        totalbiaya = 0;
        jumlahPembeli = 0;
        jLabelPembeliPenjualan.setText("Pembeli : " + nm);
        jLabelKodePenjualan.setText("Kode : " + kd);
        jLabelTotalBiayaPenjualan.setText("Total Biaya : " + totalbiaya);
        DefaultTableModel model = (DefaultTableModel) jTablePenjualan.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButtonAddPenjualanActionPerformed

    private void jButtonBatalPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalPenjualanActionPerformed
        arrayPenjualan = null;
        totalbiaya = 0;
        jumlahPembeli = 0;
        jLabelKodePenjualan.setText("Kode : ");
        jLabelTotalBiayaPenjualan.setText("Total Biaya : ");
        DefaultTableModel model = (DefaultTableModel) jTablePenjualan.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButtonBatalPenjualanActionPerformed

    private void jButtonAddItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemPenjualanActionPerformed
        cPakaian s = null;
        if (jumlahPembeli < arrayPenjualan.getMS()) {
            String m = JOptionPane.showInputDialog(this, "Masukkan Merk");
            boolean ada = false;
            for (int i = 0; i < jumlahPakaian; i++) {
                if (arrayPakaian[i].getMerk().equalsIgnoreCase(m)) {
                    ada = true;
                    s = arrayPakaian[i];
                    break;
                }
            }
            if (ada == true) {
                arrayPenjualan.addPakaian(s);
                jumlahPembeli++;
                totalbiaya = totalbiaya + s.getHarga();
                listDataPenjualan[0][0] = String.valueOf(jumlahPembeli);
                listDataPenjualan[0][1] = s.getMerk();
                listDataPenjualan[0][2] = String.valueOf(s.getHarga());
                DefaultTableModel model = (DefaultTableModel) jTablePenjualan.getModel();
                model.addRow(listDataPenjualan[0]);
                JOptionPane.showMessageDialog(this, "Tambah Sukses");
            } else {
                JOptionPane.showMessageDialog(this, "Merk Tidak Ada!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kapasitas Penuh");
        }
    }//GEN-LAST:event_jButtonAddItemPenjualanActionPerformed

    private void jButtonRemoveItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveItemPenjualanActionPerformed
        if (jumlahPembeli > 0) {
            //cari dulu merk di array object sepatu di dalam pembelian
            boolean ketemu = false;
            int indeks = 0;
            cPakaian s[] = arrayPenjualan.getPakaian();
            String id = JOptionPane.showInputDialog(this, "Masukkan Merk");
            //cek cari dulu ID di Array Pelanggan
            for (int i = 0; i < arrayPenjualan.getMS(); i++) {
                indeks = i;
                if (s[i].getMerk().equalsIgnoreCase(id)) {
                    ketemu = true;
                    break;
                }
            }
            if (ketemu == true) {
                int j = JOptionPane.showConfirmDialog(this, "Yakin dihapus");
                if (j == 0) {
                    totalbiaya = totalbiaya - s[indeks].getHarga();
                    jLabelTotalBiayaPenjualan.setText("Total Biaya : " + totalbiaya);
                    arrayPenjualan.delPakaian(id);
                    jumlahPembeli--;
                    //update isi tabel
                    DefaultTableModel model = (DefaultTableModel) jTablePenjualan.getModel();
                    model.removeRow(indeks);
                    JOptionPane.showMessageDialog(this, "Berhasil dihapus...");
                } else {
                    JOptionPane.showMessageDialog(this, "Batal dihapus!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Merk tidak ada!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kosong");
        }
    }//GEN-LAST:event_jButtonRemoveItemPenjualanActionPerformed

    private void jButtonBackPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackPenjualanActionPerformed
        MenuUI menu = new MenuUI();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItemPenjualan;
    private javax.swing.JButton jButtonAddPenjualan;
    private javax.swing.JButton jButtonBackPenjualan;
    private javax.swing.JButton jButtonBatalPenjualan;
    private javax.swing.JButton jButtonRemoveItemPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKodePenjualan;
    private javax.swing.JLabel jLabelPembeliPenjualan;
    private javax.swing.JLabel jLabelPenjualan;
    private javax.swing.JLabel jLabelTotalBiayaPenjualan;
    private javax.swing.JPanel jPanelPenjualan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePenjualan;
    // End of variables declaration//GEN-END:variables
}
